#define _POSIX_C_SOURCE 200809L
#include "notify.h"
#include "prefs_store.h"
#include "recents.h"
#include "session.h"
#include "sessions_store.h"
#include "state_detector.h"
#include "ui/grid.h"
#include "ui/prefs.h"
#include "ui/session_picker.h"
#include "ui/sidebar.h"
#include <adwaita.h>
#include <gio/gio.h>
#include <signal.h>
#include <string.h>
#include <vte/vte.h>

/* generated by gnome.compile_resources */
extern GResource *gattn_resources_get_resource(void);

static SessionList sessions;

static const char CSS[] = ".dot-idle        { color: gray;    }"
                          ".dot-working     { color: #FFC107; }"
                          ".dot-needs-input { color: #4CAF50; }"
                          ".dot-blocked     { color: #F44336; }"
                          ".dot-done        { color: #2196F3; }"
                          /* grid tile border colours — match sidebar dot colours */
                          "frame.frame-idle        { border: 2px solid gray;    }"
                          "frame.frame-working     { border: 2px solid #FFC107; }"
                          "frame.frame-needs-input { border: 2px solid #4CAF50; }"
                          "frame.frame-blocked     { border: 2px solid #F44336; }"
                          "frame.frame-done        { border: 2px solid #2196F3; }"
                          "";

static struct {
    GtkWidget       *outer_stack;
    GtkWidget       *split;
    AdwToastOverlay *overlay;
    GApplication    *gapp;
    double           zoom;       /* VTE font scale; 1.0 = default */
    GtkLabel        *zoom_label; /* percentage shown in the hamburger popover */
} app;

static GSimpleAction   *exit_grid_act;
static GtkToggleButton *grid_btn;

static void apply_prefs_to_terminal(VteTerminal *t, const GattnPrefs *p);

/* -- helpers -- */

static GtkListBox *
get_lb(void)
{
    return GTK_LIST_BOX(g_object_get_data(G_OBJECT(app.split), "gattn-listbox"));
}

static Session *
selected_session(void)
{
    GtkListBoxRow *row = gtk_list_box_get_selected_row(get_lb());
    return row ? g_object_get_data(G_OBJECT(row), "gattn-session") : NULL;
}

/* -- grid toggle (keeps exit-grid action in sync) -- */

static void toggle_grid(void); /* forward declaration */

static void
on_grid_back(GtkButton *btn, gpointer d)
{
    (void)btn;
    (void)d;
    toggle_grid();
}

/* Actions whose Alt+arrow accels clash with grid tile navigation */
static const char *const grid_blocked_actions[] = {
    "focus-sidebar",
    "focus-content",
    "next-session",
    "prev-session",
};

static void
toggle_grid(void)
{
    grid_toggle(app.outer_stack, app.split, &sessions, G_CALLBACK(on_grid_back), NULL);
    const char *cur     = gtk_stack_get_visible_child_name(GTK_STACK(app.outer_stack));
    gboolean    in_grid = cur && strcmp(cur, "grid") == 0;
    g_simple_action_set_enabled(exit_grid_act, in_grid);
    if (grid_btn)
        gtk_toggle_button_set_active(grid_btn, in_grid);
    for (gsize i = 0; i < sizeof(grid_blocked_actions) / sizeof(*grid_blocked_actions); i++) {
        GAction *act = g_action_map_lookup_action(G_ACTION_MAP(app.gapp), grid_blocked_actions[i]);
        if (act)
            g_simple_action_set_enabled(G_SIMPLE_ACTION(act), !in_grid);
    }
}

/* -- action callbacks -- */

static void
on_toggle_grid(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    toggle_grid();
}

static void
on_exit_grid(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    toggle_grid();
}

static void
on_raise(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    GtkWindow *win = gtk_application_get_active_window(GTK_APPLICATION(d));
    if (win)
        gtk_window_present(win);
}

static void
on_close_session(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    Session *s = selected_session();
    if (s && s->pid > 0)
        kill(s->pid, SIGHUP);
}

static void
on_move_session(int delta)
{
    GtkListBox *lb = get_lb();

    /* collect top-level session rows only */
    GtkListBoxRow *tops[32];
    int            ntops = 0;
    for (int i = 0; ntops < 32; i++) {
        GtkListBoxRow *r = gtk_list_box_get_row_at_index(lb, i);
        if (!r)
            break;
        Session *s = g_object_get_data(G_OBJECT(r), "gattn-session");
        if (s && s->parent_id == 0)
            tops[ntops++] = r;
    }
    if (!ntops)
        return;

    /* find current top-level position (handle subagent rows too) */
    GtkListBoxRow *sel = gtk_list_box_get_selected_row(lb);
    int            cur = 0;
    if (sel) {
        Session *ss        = g_object_get_data(G_OBJECT(sel), "gattn-session");
        int      target_id = ss ? (ss->parent_id ? ss->parent_id : ss->id) : -1;
        for (int i = 0; i < ntops; i++) {
            Session *ts = g_object_get_data(G_OBJECT(tops[i]), "gattn-session");
            if (ts && ts->id == target_id) {
                cur = i;
                break;
            }
        }
    }

    int next = ((cur + delta) % ntops + ntops) % ntops;
    gtk_list_box_select_row(lb, tops[next]);
}

static void
on_next_session(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    on_move_session(1);
}

static void
on_prev_session(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    on_move_session(-1);
}

static void
on_jump_first(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    GtkListBox *lb = get_lb();
    for (int i = 0;; i++) {
        GtkListBoxRow *row = gtk_list_box_get_row_at_index(lb, i);
        if (!row)
            break;
        Session *s = g_object_get_data(G_OBJECT(row), "gattn-session");
        if (s && s->parent_id == 0) {
            gtk_list_box_select_row(lb, row);
            break;
        }
    }
}

static void
on_jump_last(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    GtkListBox    *lb   = get_lb();
    GtkListBoxRow *last = NULL;
    for (int i = 0;; i++) {
        GtkListBoxRow *row = gtk_list_box_get_row_at_index(lb, i);
        if (!row)
            break;
        Session *s = g_object_get_data(G_OBJECT(row), "gattn-session");
        if (s && s->parent_id == 0)
            last = row;
    }
    if (last)
        gtk_list_box_select_row(lb, last);
}

static void
on_next_unattended(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    GtkListBox    *lb       = get_lb();
    GtkListBoxRow *cur      = gtk_list_box_get_selected_row(lb);
    int            start    = cur ? gtk_list_box_row_get_index(cur) + 1 : 0;
    int            n        = sessions.count;
    GtkListBoxRow *fallback = NULL;
    for (int i = 0; i < n; i++) {
        GtkListBoxRow *row = gtk_list_box_get_row_at_index(lb, (start + i) % n);
        if (!row)
            continue;
        Session *s = g_object_get_data(G_OBJECT(row), "gattn-session");
        if (!s)
            continue;
        if (s->state == SESSION_BLOCKED) {
            gtk_list_box_select_row(lb, row);
            return;
        }
        if (s->state == SESSION_NEEDS_INPUT && !fallback)
            fallback = row;
    }
    if (fallback)
        gtk_list_box_select_row(lb, fallback);
}

/* -- sub-agent detection -- */

static void
on_child_spawned(int child_pid, int parent_id, gpointer data)
{
    (void)data;
    /* already tracked? */
    for (int i = 0; i < sessions.count; i++)
        if (sessions.items[i] && sessions.items[i]->pid == child_pid)
            return;

    /* find parent */
    Session *parent = NULL;
    for (int i = 0; i < sessions.count; i++)
        if (sessions.items[i] && sessions.items[i]->id == parent_id) {
            parent = sessions.items[i];
            break;
        }
    if (!parent)
        return;

    /* read full command line from /proc/<pid>/cmdline (args separated by NUL) */
    char name[64]      = "agent";
    char full_cmd[128] = "";
    char cmdline_path[64];
    g_snprintf(cmdline_path, sizeof(cmdline_path), "/proc/%d/cmdline", child_pid);
    char *raw     = NULL;
    gsize raw_len = 0;
    if (g_file_get_contents(cmdline_path, &raw, &raw_len, NULL) && raw_len > 0) {
        for (gsize i = 0; i + 1 < raw_len; i++)
            if (raw[i] == '\0')
                raw[i] = ' ';
        raw[raw_len - 1] = '\0';
        g_strstrip(raw);
        g_strlcpy(full_cmd, raw, sizeof(full_cmd));
        /* shorten absolute paths: /a/b/exe args → /.../exe args */
        if (raw[0] == '/') {
            char *sp   = strchr(raw, ' ');
            char *base = strrchr(sp ? (char[]){ 0 } : raw, '/');
            if (!sp)
                base = strrchr(raw, '/');
            else {
                char tmp = *sp;
                *sp      = '\0';
                base     = strrchr(raw, '/');
                *sp      = tmp;
            }
            if (base && base != raw)
                g_snprintf(name, sizeof(name), "/.../%s", base + 1);
            else
                g_strlcpy(name, raw, sizeof(name));
        } else {
            g_strlcpy(name, raw, sizeof(name));
        }
        g_free(raw);
    }

    Session *child = session_create(&sessions, name);
    if (!child)
        return;
    child->parent_id = parent_id;
    child->pid       = child_pid;
    if (full_cmd[0])
        g_strlcpy(child->cmd, full_cmd, sizeof(child->cmd));
    child->is_robot = g_ascii_strncasecmp(parent->name, "claude", 6) == 0
                      || g_ascii_strncasecmp(parent->cmd, "claude", 6) == 0;
    child->terminal = parent->terminal;
    if (parent->cwd[0])
        g_strlcpy(child->cwd, parent->cwd, sizeof(child->cwd));
    sidebar_add_session(app.split, child);
    state_detector_start_child(child);
}

static void
on_child_exited(int child_pid, int parent_id, gpointer data)
{
    (void)parent_id;
    (void)data;
    for (int i = 0; i < sessions.count; i++) {
        Session *si = sessions.items[i];
        if (si && si->pid == child_pid && si->parent_id != 0) {
            int id = si->id;
            state_detector_stop(si);
            sidebar_remove_session(app.split, id);
            session_destroy(&sessions, id);
            return;
        }
    }
}

/* -- session cleanup (fires after session.c's own child-exited handler) -- */

static void
on_session_cleanup(GtkWidget *term, int status, gpointer data)
{
    (void)term;
    (void)status;
    Session *s  = data;
    int      id = s->id;

    /* stop detector before any array shifts */
    state_detector_stop(s);

    /* collect and remove child sessions */
    int child_ids[32], child_count = 0;
    for (int i = 0; i < sessions.count; i++)
        if (sessions.items[i] && sessions.items[i]->parent_id == id && child_count < 32)
            child_ids[child_count++] = sessions.items[i]->id;
    for (int i = 0; i < child_count; i++) {
        for (int j = 0; j < sessions.count; j++)
            if (sessions.items[j] && sessions.items[j]->id == child_ids[i]) {
                state_detector_stop(sessions.items[j]);
                break;
            }
        sidebar_remove_session(app.split, child_ids[i]);
        session_destroy(&sessions, child_ids[i]);
    }

    sidebar_remove_session(app.split, id);
    session_destroy(&sessions, id);
    sessions_save(&sessions);
}

/* -- session creation -- */

static void
add_session_named(GtkWidget *split, const char *cmd, const char *working_dir,
                  const char *preserved_name)
{
    char name[64] = "shell";
    if (preserved_name && *preserved_name) {
        g_strlcpy(name, preserved_name, sizeof(name));
    } else if (cmd && *cmd) {
        char tmp[256];
        g_strlcpy(tmp, cmd, sizeof(tmp));
        char *space = strchr(tmp, ' ');
        if (space)
            *space = '\0';
        const char *base = strrchr(tmp, '/');
        g_strlcpy(name, base ? base + 1 : tmp, sizeof(name));
    }
    Session *s = session_create(&sessions, name);
    if (!s)
        return;
    s->on_child_spawned      = on_child_spawned;
    s->on_child_spawned_data = NULL;
    s->on_child_exited       = on_child_exited;
    s->on_child_exited_data  = NULL;
    if (cmd && *cmd)
        g_strlcpy(s->cmd, cmd, sizeof(s->cmd));
    if (working_dir) {
        g_strlcpy(s->cwd, working_dir, sizeof(s->cwd));
        recents_add(working_dir);
    }
    session_spawn(s, (cmd && *cmd) ? cmd : NULL, working_dir);
    GattnPrefs prefs = prefs_load();
    apply_prefs_to_terminal(VTE_TERMINAL(s->terminal), &prefs);
    g_signal_connect(s->terminal, "child-exited", G_CALLBACK(on_session_cleanup), s);
    state_detector_start(s);
    notify_watch(s, app.overlay, app.gapp);
    sidebar_add_session(split, s);
    sessions_save(&sessions);
}

static inline void
add_session(GtkWidget *split, const char *cmd, const char *working_dir)
{
    add_session_named(split, cmd, working_dir, NULL);
}

static void
on_session_picked(const char *cmd, const char *dir, gpointer data)
{
    add_session((GtkWidget *)data, cmd, dir);
}

static void
on_new_session(GtkWidget *split, gpointer data)
{
    (void)data;
    GtkWindow  *win = gtk_application_get_active_window(GTK_APPLICATION(app.gapp));
    Session    *s   = selected_session();
    const char *cwd = (s && s->cwd[0]) ? s->cwd : NULL;
    session_picker_show(GTK_WIDGET(win), on_session_picked, split, cwd);
}

static void
on_resume_claude(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    GtkWindow  *win = gtk_application_get_active_window(GTK_APPLICATION(app.gapp));
    Session    *s   = selected_session();
    const char *cwd = (s && s->cwd[0]) ? s->cwd : g_get_home_dir();
    session_resume_show(GTK_WIDGET(win), on_session_picked, app.split, cwd);
}

static void
apply_prefs_to_terminal(VteTerminal *t, const GattnPrefs *p)
{
    PangoFontDescription *fd = pango_font_description_from_string(p->font);
    vte_terminal_set_font(t, fd);
    pango_font_description_free(fd);
    vte_terminal_set_font_scale(t, app.zoom);
    GdkRGBA fg, bg;
    if (g_strcmp0(p->theme, "Default") == 0) {
        gboolean dark = adw_style_manager_get_dark(adw_style_manager_get_default());
        gdk_rgba_parse(&fg, dark ? "#dedede" : "#2b2b2b");
        gdk_rgba_parse(&bg, dark ? "#242424" : "#fafafa");
    } else {
        fg = (GdkRGBA){ 1, 1, 1, 1 };
        bg = (GdkRGBA){ 0, 0, 0, 1 };
        gdk_rgba_parse(&fg, p->fg);
        gdk_rgba_parse(&bg, p->bg);
    }
    vte_terminal_set_colors(t, &fg, &bg, NULL, 0);
}

static void
on_prefs_changed(gpointer data)
{
    (void)data;
    GattnPrefs p = prefs_load();
    for (int i = 0; i < sessions.count; i++)
        if (sessions.items[i] && sessions.items[i]->terminal)
            apply_prefs_to_terminal(VTE_TERMINAL(sessions.items[i]->terminal), &p);
}

static void
on_dark_changed(AdwStyleManager *sm, GParamSpec *ps, gpointer d)
{
    (void)sm;
    (void)ps;
    (void)d;
    on_prefs_changed(NULL);
}

static void
on_preferences(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    GtkWindow *win = gtk_application_get_active_window(GTK_APPLICATION(app.gapp));
    prefs_dialog_show(GTK_WIDGET(win), on_prefs_changed, NULL);
}

static void
on_about(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    AdwAboutDialog *dlg = ADW_ABOUT_DIALOG(adw_about_dialog_new());
    adw_about_dialog_set_application_name(dlg, "gattn");
    adw_about_dialog_set_application_icon(dlg, "org.mmxgn.gattn");
    adw_about_dialog_set_version(dlg, "0.1.0");
    adw_about_dialog_set_comments(dlg, "GNOME attention hub for Claude Code sessions");
    adw_about_dialog_set_website(dlg, "https://github.com/mmxgn/gattn");
    adw_about_dialog_set_issue_url(dlg, "https://github.com/mmxgn/gattn/issues");
    adw_about_dialog_set_license_type(dlg, GTK_LICENSE_GPL_3_0);
    const char *devs[] = { "mmxgn", NULL };
    adw_about_dialog_set_developers(dlg, devs);
    GtkWindow *win = gtk_application_get_active_window(GTK_APPLICATION(app.gapp));
    adw_dialog_present(ADW_DIALOG(dlg), GTK_WIDGET(win));
}

static void
on_rename_session(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    Session   *s   = selected_session();
    GtkWindow *win = gtk_application_get_active_window(GTK_APPLICATION(app.gapp));
    if (s && win)
        sidebar_rename_session(s, GTK_WIDGET(win));
}

static void
on_focus_sidebar(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    adw_navigation_split_view_set_show_content(ADW_NAVIGATION_SPLIT_VIEW(app.split), FALSE);
    gtk_widget_grab_focus(GTK_WIDGET(get_lb()));
}

/* -- zoom, fullscreen, color-scheme -- */

static void
apply_zoom_to_all(void)
{
    for (int i = 0; i < sessions.count; i++)
        if (sessions.items[i] && sessions.items[i]->terminal)
            vte_terminal_set_font_scale(VTE_TERMINAL(sessions.items[i]->terminal), app.zoom);
    if (app.zoom_label) {
        char buf[16];
        g_snprintf(buf, sizeof(buf), "%d%%", (int)(app.zoom * 100 + 0.5));
        gtk_label_set_text(app.zoom_label, buf);
    }
}

static void
on_zoom_in(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    app.zoom = MIN(app.zoom + 0.1, 3.0);
    apply_zoom_to_all();
}
static void
on_zoom_out(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    app.zoom = MAX(app.zoom - 0.1, 0.5);
    apply_zoom_to_all();
}
static void
on_zoom_reset(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    app.zoom = 1.0;
    apply_zoom_to_all();
}

static void
on_fullscreen(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    GtkWindow *win = gtk_application_get_active_window(GTK_APPLICATION(app.gapp));
    if (!win)
        return;
    if (gtk_window_is_fullscreen(win))
        gtk_window_unfullscreen(win);
    else
        gtk_window_fullscreen(win);
}

static void
on_color_scheme(GSimpleAction *a, GVariant *param, gpointer d)
{
    (void)d;
    if (!param)
        return;
    const char    *v      = g_variant_get_string(param, NULL);
    AdwColorScheme scheme = ADW_COLOR_SCHEME_DEFAULT;
    if (g_strcmp0(v, "light") == 0)
        scheme = ADW_COLOR_SCHEME_FORCE_LIGHT;
    else if (g_strcmp0(v, "dark") == 0)
        scheme = ADW_COLOR_SCHEME_FORCE_DARK;
    adw_style_manager_set_color_scheme(adw_style_manager_get_default(), scheme);
    g_simple_action_set_state(a, param);
    GattnPrefs p = prefs_load();
    g_strlcpy(p.color_scheme, v, sizeof(p.color_scheme));
    prefs_save(&p);
}

static void
on_focus_content(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    adw_navigation_split_view_set_show_content(ADW_NAVIGATION_SPLIT_VIEW(app.split), TRUE);
    Session *s = selected_session();
    if (s)
        gtk_widget_grab_focus(s->terminal);
}

static void
on_show_diff(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    Session   *s   = selected_session();
    GtkWindow *win = gtk_application_get_active_window(GTK_APPLICATION(app.gapp));
    if (s && win)
        sidebar_show_diff(s, GTK_WIDGET(win));
}

static void
on_open_folder(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    Session *s = selected_session();
    if (!s)
        return;
    const char *cwd = s->cwd[0] ? s->cwd : g_get_home_dir();
    char       *uri = g_strdup_printf("file://%s", cwd);
    g_app_info_launch_default_for_uri(uri, NULL, NULL);
    g_free(uri);
}

static void
on_open_shell_here(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    Session *s = selected_session();
    if (!s)
        return;
    const char *cwd = s->cwd[0] ? s->cwd : g_get_home_dir();
    add_session(app.split, NULL, cwd);
}

static void
on_new_session_action(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    on_new_session(app.split, NULL);
}

static void
on_shell_here(GtkWidget *split, const char *cwd, gpointer d)
{
    (void)d;
    add_session(split, NULL, cwd);
}

static void
on_compact_level_0_apply(gpointer d)
{
    (void)d;
    sidebar_set_compact_level(app.split, 0);
}
static void
on_compact_level_2_apply(gpointer d)
{
    (void)d;
    sidebar_set_compact_level(app.split, 2);
}

static void
on_toggle_search(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    sidebar_toggle_search(app.split);
}

static void
on_term_copy(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    Session *s = selected_session();
    if (s && s->terminal)
        vte_terminal_copy_clipboard_format(VTE_TERMINAL(s->terminal), VTE_FORMAT_TEXT);
}

static void
on_term_paste(GSimpleAction *a, GVariant *p, gpointer d)
{
    (void)a;
    (void)p;
    (void)d;
    Session *s = selected_session();
    if (s && s->terminal)
        vte_terminal_paste_clipboard(VTE_TERMINAL(s->terminal));
}

/* -- startup -- */

static void
register_action(GActionMap *map, const char *name, GCallback cb, gpointer data)
{
    GSimpleAction *act = g_simple_action_new(name, NULL);
    g_signal_connect(act, "activate", cb, data);
    g_action_map_add_action(map, G_ACTION(act));
    g_object_unref(act);
}

static void
on_activate(AdwApplication *app_obj, gpointer data)
{
    (void)data;
    app.gapp = G_APPLICATION(app_obj);
    app.zoom = 1.0;

    gtk_icon_theme_add_resource_path(gtk_icon_theme_get_for_display(gdk_display_get_default()),
                                     "/org/mmxgn/gattn/icons");

    GtkCssProvider *provider = gtk_css_provider_new();
    gtk_css_provider_load_from_string(provider, CSS);
    gtk_style_context_add_provider_for_display(gdk_display_get_default(),
                                               GTK_STYLE_PROVIDER(provider),
                                               GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
    g_object_unref(provider);

    app.overlay = ADW_TOAST_OVERLAY(adw_toast_overlay_new());

    app.split = sidebar_new(&sessions, on_new_session, NULL);
    sidebar_set_shell_here(app.split, on_shell_here, NULL);
    app.zoom_label = GTK_LABEL(g_object_get_data(G_OBJECT(app.split), "gattn-zoom-label"));

    AdwHeaderBar *content_hdr = g_object_get_data(G_OBJECT(app.split), "gattn-content-header");
    grid_btn                  = GTK_TOGGLE_BUTTON(gtk_toggle_button_new());
    gtk_button_set_icon_name(GTK_BUTTON(grid_btn), "view-grid-symbolic");
    gtk_widget_set_tooltip_text(GTK_WIDGET(grid_btn), "Grid view (Ctrl+G)");
    g_signal_connect_swapped(grid_btn, "clicked", G_CALLBACK(toggle_grid), NULL);
    adw_header_bar_pack_end(content_hdr, GTK_WIDGET(grid_btn));

    app.outer_stack = gtk_stack_new();
    gtk_stack_add_named(GTK_STACK(app.outer_stack), app.split, "split");
    adw_toast_overlay_set_child(app.overlay, app.outer_stack);

    GActionMap *map = G_ACTION_MAP(app_obj);
    register_action(map, "toggle-grid", G_CALLBACK(on_toggle_grid), NULL);
    register_action(map, "new-session", G_CALLBACK(on_new_session_action), NULL);
    register_action(map, "close-session", G_CALLBACK(on_close_session), NULL);
    register_action(map, "next-session", G_CALLBACK(on_next_session), NULL);
    register_action(map, "prev-session", G_CALLBACK(on_prev_session), NULL);
    register_action(map, "next-unattended", G_CALLBACK(on_next_unattended), NULL);
    register_action(map, "jump-first", G_CALLBACK(on_jump_first), NULL);
    register_action(map, "jump-last", G_CALLBACK(on_jump_last), NULL);
    register_action(map, "raise", G_CALLBACK(on_raise), app_obj);
    register_action(map, "show-diff", G_CALLBACK(on_show_diff), NULL);
    register_action(map, "open-folder", G_CALLBACK(on_open_folder), NULL);
    register_action(map, "open-shell-here", G_CALLBACK(on_open_shell_here), NULL);
    register_action(map, "resume-claude", G_CALLBACK(on_resume_claude), NULL);
    register_action(map, "focus-sidebar", G_CALLBACK(on_focus_sidebar), NULL);
    register_action(map, "focus-content", G_CALLBACK(on_focus_content), NULL);
    register_action(map, "preferences", G_CALLBACK(on_preferences), NULL);
    register_action(map, "about", G_CALLBACK(on_about), NULL);
    register_action(map, "rename-session", G_CALLBACK(on_rename_session), NULL);
    register_action(map, "toggle-search", G_CALLBACK(on_toggle_search), NULL);
    register_action(map, "term-copy", G_CALLBACK(on_term_copy), NULL);
    register_action(map, "term-paste", G_CALLBACK(on_term_paste), NULL);
    register_action(map, "zoom-in", G_CALLBACK(on_zoom_in), NULL);
    register_action(map, "zoom-out", G_CALLBACK(on_zoom_out), NULL);
    register_action(map, "zoom-reset", G_CALLBACK(on_zoom_reset), NULL);
    register_action(map, "fullscreen", G_CALLBACK(on_fullscreen), NULL);

    /* Stateful action driving the three theme buttons in the hamburger. */
    GattnPrefs     saved_prefs = prefs_load();
    const char    *saved_cs    = saved_prefs.color_scheme[0] ? saved_prefs.color_scheme : "auto";
    GSimpleAction *cs_act      = g_simple_action_new_stateful("color-scheme", G_VARIANT_TYPE_STRING,
                                                              g_variant_new_string(saved_cs));
    g_signal_connect(cs_act, "activate", G_CALLBACK(on_color_scheme), NULL);
    g_action_map_add_action(map, G_ACTION(cs_act));
    g_object_unref(cs_act);
    /* Apply immediately so the style manager is in sync from the first frame. */
    {
        AdwColorScheme sc = ADW_COLOR_SCHEME_DEFAULT;
        if (g_strcmp0(saved_cs, "light") == 0)
            sc = ADW_COLOR_SCHEME_FORCE_LIGHT;
        else if (g_strcmp0(saved_cs, "dark") == 0)
            sc = ADW_COLOR_SCHEME_FORCE_DARK;
        adw_style_manager_set_color_scheme(adw_style_manager_get_default(), sc);
    }
    g_signal_connect(adw_style_manager_get_default(), "notify::dark", G_CALLBACK(on_dark_changed),
                     NULL);

    /* exit-grid is disabled until grid mode is entered */
    exit_grid_act = g_simple_action_new("exit-grid", NULL);
    g_simple_action_set_enabled(exit_grid_act, FALSE);
    g_signal_connect(exit_grid_act, "activate", G_CALLBACK(on_exit_grid), NULL);
    g_action_map_add_action(map, G_ACTION(exit_grid_act));
    g_object_unref(exit_grid_act);

    AdwApplicationWindow *win
        = ADW_APPLICATION_WINDOW(adw_application_window_new(GTK_APPLICATION(app_obj)));
    gtk_window_set_default_size(GTK_WINDOW(win), 1200, 700);
    gtk_window_set_icon_name(GTK_WINDOW(win), "org.mmxgn.gattn");
    adw_application_window_set_content(win, GTK_WIDGET(app.overlay));

    /* Adaptive sidebar: hide cwd at narrow widths, then collapse the split.
       Row action buttons are hover/focus-revealed (see sidebar.c), so no
       breakpoint is needed for them. */
    AdwBreakpoint *bp_hide_cwd
        = adw_breakpoint_new(adw_breakpoint_condition_parse("max-width: 700sp"));
    g_signal_connect_swapped(bp_hide_cwd, "apply", G_CALLBACK(on_compact_level_2_apply), NULL);
    g_signal_connect_swapped(bp_hide_cwd, "unapply", G_CALLBACK(on_compact_level_0_apply), NULL);
    adw_application_window_add_breakpoint(win, bp_hide_cwd);

    AdwBreakpoint *bp_collapse
        = adw_breakpoint_new(adw_breakpoint_condition_parse("max-width: 500sp"));
    GValue vtrue = G_VALUE_INIT;
    g_value_init(&vtrue, G_TYPE_BOOLEAN);
    g_value_set_boolean(&vtrue, TRUE);
    adw_breakpoint_add_setter(bp_collapse, G_OBJECT(app.split), "collapsed", &vtrue);
    /* Also push the content page so the terminal is the visible root on squeeze,
       not the sidebar. */
    adw_breakpoint_add_setter(bp_collapse, G_OBJECT(app.split), "show-content", &vtrue);
    g_value_unset(&vtrue);
    adw_application_window_add_breakpoint(win, bp_collapse);

    gtk_window_present(GTK_WINDOW(win));

    SavedSession saved[32];
    int          nsaved = sessions_load(saved, 32);
    if (nsaved > 0) {
        for (int i = 0; i < nsaved; i++)
            add_session_named(app.split, saved[i].cmd[0] ? saved[i].cmd : NULL,
                              saved[i].dir[0] ? saved[i].dir : NULL,
                              saved[i].name[0] ? saved[i].name : NULL);
    } else {
        session_picker_show(GTK_WIDGET(win), on_session_picked, app.split, NULL);
    }
}

int
main(int argc, char *argv[])
{
    g_resources_register(gattn_resources_get_resource());
    session_list_init(&sessions);
    /* ponytail: NON_UNIQUE lets multiple gattn instances coexist;
       otherwise a second launch activates the first and reparents its VTEs. */
    AdwApplication *a = adw_application_new("org.mmxgn.gattn", G_APPLICATION_NON_UNIQUE);
    g_signal_connect(a, "activate", G_CALLBACK(on_activate), NULL);

    struct {
        const char *action;
        const char *accel;
    } bindings[] = {
        { "app.toggle-grid", "<Control>g" },
        { "app.new-session", "<Control>n" },
        { "app.close-session", "<Control><Shift>w" },
        { "app.next-session", "<Control>Tab" },
        { "app.prev-session", "<Control><Shift>Tab" },
        { "app.next-unattended", "<Control><Shift>a" },
        { "app.jump-first", "<Control>Prior" },
        { "app.jump-last", "<Control>Next" },
        { "app.exit-grid", "<Control>g" },
        { "app.show-diff", "<Control><Shift>d" },
        { "app.open-folder", "<Control><Shift>o" },
        { "app.open-shell-here", "<Control><Shift>t" },
        { "app.resume-claude", "<Control><Shift>r" },
        { "app.focus-sidebar", "<Alt>Left" },
        { "app.focus-content", "<Alt>Right" },
        { "app.rename-session", "F2" },
        { "app.toggle-search", "<Control>f" },
        { "app.zoom-in", "<Control>plus" },
        { "app.zoom-out", "<Control>minus" },
        { "app.zoom-reset", "<Control>0" },
        { "app.fullscreen", "F11" },
        { "app.term-copy", "<Control><Shift>c" },
        { "app.term-paste", "<Control><Shift>v" },
    };
    for (size_t i = 0; i < sizeof(bindings) / sizeof(*bindings); i++) {
        const char *accels[] = { bindings[i].accel, NULL };
        gtk_application_set_accels_for_action(GTK_APPLICATION(a), bindings[i].action, accels);
    }
    /* multi-accel overrides (must come after the loop) */
    gtk_application_set_accels_for_action(
        GTK_APPLICATION(a), "app.next-session",
        (const char *[]){ "<Control>Tab", "<Alt>Down", "<Alt>j", NULL });
    gtk_application_set_accels_for_action(
        GTK_APPLICATION(a), "app.prev-session",
        (const char *[]){ "<Control><Shift>Tab", "<Alt>Up", "<Alt>k", NULL });
    gtk_application_set_accels_for_action(GTK_APPLICATION(a), "app.focus-sidebar",
                                          (const char *[]){ "<Alt>Left", "<Alt>h", NULL });
    gtk_application_set_accels_for_action(GTK_APPLICATION(a), "app.focus-content",
                                          (const char *[]){ "<Alt>Right", "<Alt>l", NULL });

    int status = g_application_run(G_APPLICATION(a), argc, argv);
    g_object_unref(a);
    return status;
}
